import {FITNESS} from './activity-data.js';
import {maxStamina,hasSwiftness,beginTraining,startRace,settleRace,takeSwiftness} from './activities.js';
import {portraitSVG} from './data.js';

export function createActivityUI(s,{open,close,changed,toast,playSound,refreshStation}){
 const $=q=>document.querySelector(q);
 function trainingCard(){return `<section class="job-card"><span class="eyebrow">A LITTLE STRONGER, EVERY DAY</span><h3>Maximum stamina: ${maxStamina(s)} / ${FITNESS.max}</h3><p>Each pull-up takes 3 seconds, costs 3 stamina, and permanently adds 1 to your maximum stamina. Rest or eat berries between sets.</p><div class="job-track"><i id="training-progress"></i></div><p id="training-time" role="status"></p><button id="train" class="primary" data-focus ${s.training||maxStamina(s)>=FITNESS.max?'disabled':''}>${maxStamina(s)>=FITNESS.max?'Fully trained!':'Do a pull-up · +1 max stamina'}</button><p class="note">Stay at the bar until the repetition is complete. Leaving cancels it.</p></section>`;}
 function bindTraining(id){if(!$('#train'))return;$('#train').onclick=()=>{const result=beginTraining(s,id);if(result.error)return toast(result.error,'error');changed();refreshStation();};updateTraining();}
 function updateTraining(){if(!$('#training-progress'))return;$('#training-progress').style.width=(s.training?Math.min(100,s.training.elapsed/FITNESS.trainingSeconds*100):0)+'%';$('#training-time').textContent=s.training?`Pull… hold… ${Math.max(1,Math.ceil(FITNESS.trainingSeconds-s.training.elapsed))}s`:`${Math.floor(s.energy)} / ${maxStamina(s)} stamina available`;}
 function showWalter(){
  const last=s.race.last;
  open('walter','Walter “Lightning” Whitcomb','80 years old. Zero intention of slowing down.',`<div class="person-heading">${portraitSVG('walter')}<small>The Boundary Dash</small></div><p class="speech">“I bet you one wood you can’t beat me to the other flag. Eighty years of practice, kid. My knees file complaints; I don’t read them.”</p><p class="note">A straight race along the northern boundary. Follow the two flagged lanes ${s.race.side==='west'?'east →':'← west'}. Hold <strong>Shift + ${s.race.side==='west'?'D':'A'}</strong> to sprint, or turn on <strong>Run</strong> and hold the thumbstick ${s.race.side==='west'?'right':'left'}. Sprinting uses 8 stamina per second.</p><p class="note">Entry: <strong>1 wood</strong>. Win: collect both stakes, <strong>2 wood</strong>.<br>Walter gives you a breather before every start, refilling your current maximum stamina. Food and rest wait until after the race. Leaving the lanes forfeits your stake.</p><p class="note">Your record: ${s.race.wins} wins · ${s.race.losses} losses.<br>Maximum stamina: ${maxStamina(s)} / 100 · ${hasSwiftness(s)?'Garden swiftness: +5% sprint speed':'Garden swiftness: not yet planted'}</p>${last?`<p class="note">${last.won?'“Well, I’ll be. Again?”':last.forfeit?'“The finish line’s over here, kid!”':'“Close? Close is how I describe my seventies.”'}<br>Training builds endurance. Nell’s eastern woodland trail hides a golden flower with an unusual effect when planted at home.</p>`:''}<div class="actions"><button id="race-start" class="primary" data-focus ${s.race.active?'disabled':''}>Bet 1 wood · race Walter</button><button id="race-leave" class="secondary">Maybe later.</button></div>`,'small');
  $('#race-start').onclick=()=>{const result=startRace(s);if(result.error)return toast(result.error,'error');close();changed(true);};$('#race-leave').onclick=close;
 }
 function showRaceResult(result){
  open('race-result',result.won?'You beat Lightning!':result.forfeit?'Off the course.':result.margin<.5?'Walter wins by a whisker.':'Walter wins the race.',result.forfeit?'The bet goes to Walter.':result.won?'The world’s fastest 80-year-old has met his match.':'He has been training since before your axe was rusty.',`<p class="speech">“${result.won?'I demand a recount of your legs. Same bet, other direction?':result.forfeit?'Scenic route? Respectable choice. Terrible racing strategy.':'Eighty years young, kid. That’s experience with excellent shoes.'}”</p><p class="note">${result.won?'You collected 2 wood: your stake and Walter’s.':'Walter keeps your 1 wood stake.'}${!result.forfeit?`<br>Finish gap: ${result.margin.toFixed(2)} seconds.`:''}<br>Record: ${s.race.wins} wins · ${s.race.losses} losses.</p><p class="note">${!result.won?'A pull-up bar builds the endurance to sprint the whole course. A planted flower of swiftness gives you the last little burst of speed.<br>':''}Walter waits at the ${s.race.side==='west'?'western':'eastern'} flag. Meet him there for another race in the other direction. There is no limit to rematches.</p><button id="race-done" class="primary" data-focus>Back to the woods</button>`,'small');$('#race-done').onclick=close;
 }
 function showSwiftness(){
  const result=takeSwiftness(s);if(result.error)return toast(result.error,'error');changed();
  open('flower','Flower of swiftness','A golden secret in the eastern woods.',`<p class="speech">Narrow petals lean into a wind you can’t quite feel. Your boots suddenly seem very heavy.</p><p class="note">${result.already?'You already took a cutting from this flower.':'You carefully take a cutting. It is in your backpack.'}<br>Plant the cutting in an empty woodland planter in your garden. While it grows there, Luke sprints <strong>5% faster</strong>. It does not need to be eaten, and it works anywhere in the woods.</p><p class="note">Moving the planter keeps the flower growing. Packing it returns the cutting and pauses the bonus until you plant it again.</p>`,'small');playSound('gather');
 }
 function activityJournal(){return `<article class="quest"><h3>A stronger stride</h3><p>Maximum stamina: ${maxStamina(s)} / 100. Build a woodland pull-up bar at a workbench with 2 wood and 1 iron ingot. Each completed pull-up adds 1 maximum stamina.</p><small>Shift to sprint · 8 stamina / second · ${hasSwiftness(s)?'Garden swiftness active: +5% speed':'Find a golden flower along the trail north of Nell’s maple grove.'}</small></article><article class="quest"><h3>Beat the world’s fastest 80-year-old</h3><p>Walter “Lightning” Whitcomb waits at the flagged northern boundary track. Follow the western trail north past the orchard, then head to the northern edge. Bet 1 wood whenever you want a race.</p><small>${s.race.wins} wins · ${s.race.losses} losses · unlimited rematches</small></article>`;}
 function forfeit(){const result=settleRace(s,false,0,true);if(result){changed(true);showRaceResult(result);}}
 return {trainingCard,bindTraining,updateTraining,showWalter,showRaceResult,showSwiftness,activityJournal,forfeit};
}
