import {ITEMS,portraitSVG} from './data.js';
import {OLGA_QUESTS,BUNKER_CACHES} from './story-data.js';
import {acceptOlga,completeOlga,olgaStatus,takeMoonbell,enterBunker,leaveBunker,lootBunker,hermitSaying} from './stories.js';

import {BUNKER_ROOMS,BUNKER_NOTES} from './bunker-data.js';
import {bunkerAction} from './bunker.js';

export function createStoryUI(s,{open,close,changed,toast,playSound}){
 const $=id=>document.getElementById(id);
 const names=r=>Object.entries(r).map(([k,v])=>v+' '+ITEMS[k].short).join(' · ');
 function storyJournal(){return `<article class="quest olga-story"><h3>Olga · a life taking root</h3><p>${s.olga.step===4?'Olga lives with you.':s.olga.active?olgaStatus(s).detail:'Talk to Olga '+(s.olga.step===0?'at the lost orchard, west of the north trail.':'to hear what is on her mind.')}</p><ol>${OLGA_QUESTS.map((q,i)=>`<li class="${s.olga.step===i?'current':''}">${i<s.olga.step?'✓ ':''}${q.name}${i===s.olga.step?' · '+(s.olga.active?'in progress':'available'):''}</li>`).join('')}</ol>${s.olga.active?'<p>'+OLGA_QUESTS[s.olga.step].objective+'</p>':''}</article><article class="quest"><h3>Below the ridge</h3><p>${s.bunker.open?'Explore beyond the old entrance rooms. Cut service shelves with Space, mine cave-ins with a pick, restore the generator, and drain the lower passages. M tracks the sectors you have visited.':'Find the abandoned bunker northeast of Jo’s workshop. Forge a crowbar with 4 iron ingots and 2 wood; collect it before visiting the hatch.'}</p><small>${Object.keys(s.bunker.looted).length} / ${Object.keys(BUNKER_CACHES).length} caches searched · ${Object.keys(s.bunker.rooms).length} / ${BUNKER_ROOMS.length} sectors visited · ${Object.keys(s.bunker.read).length} / ${Object.keys(BUNKER_NOTES).length} notes read.<br>Generator: ${s.bunker.power?'running':'offline'} · Lower passages: ${s.bunker.drained?'drained':'flooded'} · Salvage plans: ${s.bunker.blueprint?'recovered':'undiscovered'}</small></article>`;}
 function showOlga(){
  const o=s.olga,q=OLGA_QUESTS[o.step],status=olgaStatus(s);
  if(!q){open('person','Olga','At home with Luke',`<div class="person-heading">${portraitSVG('olga')}<small>A life taking root · complete</small></div><p class="speech">“${['I used to wonder what home would feel like. Turns out it’s the sound of your axe outside and a moonbell in the garden.','Everett asked if we have a guest wing. I told him we have a spare mug. He looked frightened.','Go explore. I’ll be here when you get back. Unless I’m admiring that moonbell again.'][s.day%3]}”</p><p class="note">Olga has moved into the room you built. Your life in the woods keeps growing.</p><button id="olga-leave" class="primary" data-focus>See you at home.</button>`,'small');$('olga-leave').onclick=close;return;}
  const onDate=o.step===2&&o.active;
  open('person','Olga',onDate?'Your date · the heron overlook':'Gardener · the lost orchard',`<div class="person-heading">${portraitSVG('olga')}<small>${q.name} · ${o.step+1} / 4</small></div><p class="speech">“${onDate?'You made it. I saved you the part of the blanket without a pinecone. Sit with me? The heron has been judging my sandwiches.':q.intro}”</p><p class="note">${q.objective}</p>${o.active?'<p class="story-progress">'+status.detail+'</p>':''}<p class="note">${o.step===1?'Olga’s invitation to a date · ':o.step===3?'Olga moves into your home · ':''}${names(q.reward)}</p><div class="actions"><button id="olga-action" class="primary" data-focus>${!o.active?o.step===2?'Yes. I’d love to go on a date.':o.step===3?'I’d love for you to move in.':'I’d like to do that.':onDate?'Stay for the picnic.':o.step===0?'How did I do?':o.step===1?'Come see the moonbell.':'Your room is ready.'}</button><button id="olga-leave" class="secondary">See you soon.</button></div>`,'small');
  $('olga-leave').onclick=close;
  $('olga-action').onclick=()=>{
   if(!o.active){const result=acceptOlga(s);if(result.error)return toast(result.error,'error');changed(true);close();toast(o.step===2?'Olga will meet you at the heron overlook.':q.name+' added to your journal.');return;}
   const result=completeOlga(s);if(result.error)return toast(result.error,'error');changed(true);playSound('build');
   open('person','Olga',o.step===4?'Welcome home.':o.step===2?'A picnic invitation.':o.step===3?'An afternoon worth keeping.':'A cut above.',`<div class="person-heading">${portraitSVG('olga')}<small>${q.name} · complete</small></div><p class="speech">“${result.text}”</p><p class="note">${names(result.reward)}${o.step===2?'<br>Talk to Olga again to accept her date invitation.':o.step===3?'<br>Find Olga back at the orchard when you’re ready to talk about what comes next.':o.step===4?'<br>Olga is now at your house. You can keep building, exploring, and visiting her.':'<br>Talk to Olga again whenever you like.'}</p><button id="olga-done" class="primary" data-focus>${o.step===4?'See you at home.':'That sounds lovely.'}</button>`,'small');$('olga-done').onclick=close;
  };
 }
 function showHermit(){
  const result=hermitSaying(s);if(result.error)return toast(result.error,'error');changed();
  open('person','Gerald “Abandoned” Moss','Resident hermit · no errands, thank you',`<div class="person-heading">${portraitSVG('hermit')}<small>Occupancy: one, allegedly.</small></div><p class="speech">“${result.text}”</p><p class="note">Past the collapsed shelves to the east: old workshops, barracks, and lower tunnels. Space chops debris or mines rock. The grow tray replenishes daily. Gerald has no errands for you—he is very proud of this.</p><div class="actions"><button id="hermit-more" class="secondary">Any other wisdom?</button><button id="hermit-leave" class="primary" data-focus>I’ll leave you to it.</button></div>`,'small');$('hermit-more').onclick=showHermit;$('hermit-leave').onclick=close;
 }
 function showStoryNode(n){
  if(['bunkergate','bunkercontrol','bunkernote','bunkergarden'].includes(n.type)){
   const operate=()=>{const result=bunkerAction(s,n.id);if(result.error)return toast(result.error,'error');changed(true);if(result.changed)playSound('build');open('bunker-event',n.name,result.changed?'Something stirs beneath the woods.':'A place with a past.','<p class="speech">'+result.text+'</p>'+(result.reward?'<p class="note">Found '+names(result.reward)+'.</p>':''),'small');};
   if(n.type==='bunkercontrol'&&!s.bunker[n.action]){open('bunker-control',n.name,n.action==='power'?'Restore the old electrical system.':'Make a way into the lower levels.','<p class="speech">'+(n.action==='power'?'An engine the size of a small car. Most of it is intact; the wiring and coupling need work.':'The control wheel is stiff. With power restored, these pumps could clear the flooded stairs into the cistern and crystal galleries.')+'</p><p class="note">'+(n.action==='power'?'Repair uses 6 machine scrap and 4 copper wire from your backpack.':'Requires a running generator in the hall one floor north. No extra materials needed.')+'</p><button id="bunker-operate" class="primary" data-focus>'+(n.action==='power'?'Repair and start the generator':'Start the drainage pumps')+'</button>','small');$('bunker-operate').onclick=operate;}else operate();return;
  }
  if(n.type==='bunkerexit'){const r=leaveBunker(s);if(r.error)return toast(r.error,'error');changed(true);toast('Fresh air. A suspiciously nice change.');return;}
  if(n.type==='bunker'){
   open('bunker','A door under the pines.','Abandoned bunker · Hemlock Ridge',`<p class="speech">${s.bunker.open?'The hatch swings open. A handwritten sign below reads: “SOLICITORS WILL BE GIVEN OPINIONS.”':'A concrete entrance emerges from the moss. The hatch is rusted shut. Behind it, someone coughs and then very loudly pretends to be a pipe.'}</p><p class="note">${s.bunker.open?'The crowbar has done its job. The entrance stays open.':s.inventory.crowbar?'Your forged crowbar should free the hatch. You keep it after opening.':'Make a crowbar at a toolsmith’s forge: 4 iron ingots + 2 wood. Collect it from the forge, then bring it here.'}</p><button id="bunker-enter" class="primary" data-focus>${s.bunker.open?'Climb down into the bunker.':'Pry open the hatch and climb down.'}</button>`,'small');
   $('bunker-enter').onclick=()=>{const result=enterBunker(s);if(result.error)return toast(result.error,'error');close();changed(true);toast('Chop salvage, mine rock, and interact with old machinery. Follow the eastern service passage.');};return;
  }
  if(n.type==='rareplant'){
   const result=takeMoonbell(s);if(result.error)return toast(result.error,'error');changed(true);
   open('plant','A little moonlight, rooted.','Silver-blue moonbell',`<p class="speech">A silver-blue flower grows in the shade. You take one rooted cutting, leaving the parent plant to flourish.</p><p class="note">+1 moonbell cutting. Craft a woodland planter at a workbench, place it in your garden, then interact with it to plant. Packing the planter returns the cutting safely.</p>`,'small');return;
  }
  const result=lootBunker(s,n.id);if(result.error)return toast(result.error,'error');changed(true);
  open('salvage',n.type==='growtray'?'The very quiet roommates.':BUNKER_CACHES[n.cache].name,'A second life for forgotten things.',`<p class="speech">${result.text}</p>${result.reward?'<p class="note">Found '+names(result.reward)+'.'+(result.blueprint?'<br>New forge recipe: reclaim high-grade steel from scrap.':'')+'<br>Smelt machine scrap into iron at a kiln. Make glow lantern kits with scrap, copper wire, and lantern caps at a workbench.</p>':''}`,'small');
 }
 return {showOlga,showHermit,showStoryNode,storyJournal};
}
