import {ITEMS,AXE_TIERS,PICK_TIERS,TREE_TIERS,ROCK_TIERS,REGIONS,PEOPLE,SIDE_QUESTS,DISCOVERIES,itemIcon,portraitSVG} from './data.js';
import {BUILDABLES,ALL_RECIPES,RECIPE_BY_ID,BRIDGE_COST,houseProgress,placementBlock,snapPoint,nearStructure} from './construction.js';
import {startJob,recipeBlock,scaledCost,jobDuration,jobOutput,collectStation,cancelJob,placeStructure,moveStructure,packStructure,getStructure,affordable,turnInQuest,repairBridge,rest,gatheringReady} from './state.js';
import {BRIDGE,CAMP} from './world.js';
import {drawMap} from './renderer.js';
import {createStoryUI} from './story-ui.js';
import {plantMoonbell} from './stories.js';
const $=s=>document.querySelector(s);
const names=output=>Object.entries(output).map(([k,n])=>`${n} ${ITEMS[k]?.short||k}`).join(' · ');
export function createUI(s,renderer,hooks){
 let modal=null,stationId=null,group=null,batch=1,placement=null,bagTab='items';
 const {changed,toast,clearKeys,playSound}=hooks;
 const isTouch=()=>!!hooks.controls?.()?.enabled;
 const {showOlga,showHermit,showStoryNode,storyJournal}=createStoryUI(s,{open,close,changed,toast,playSound});
 const costHTML=cost=>Object.entries(cost).map(([k,n])=>`<span class="${s.inventory[k]<n?'missing':''}">${n} ${ITEMS[k].short} <small>(${s.inventory[k]} held)</small></span>`).join('');
 function open(type,title,subtitle,body,size=''){
  modal=type;clearKeys();$('#hud').inert=true;
  $('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${size}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-header"><span class="eyebrow">LUKE’S WOODLAND JOURNAL</span><h2 id="modal-title">${title}</h2><p>${subtitle}</p><button class="modal-close" aria-label="Close panel">×</button></header><div class="modal-body">${body}</div><footer class="modal-footer"><span class="keyboard-hint"><kbd>↑ ↓</kbd> choose</span><span class="keyboard-hint"><kbd>ENTER</kbd> confirm</span><span class="keyboard-hint"><kbd>ESC</kbd> return to the woods</span><span class="touch-hint">Tap to choose · swipe this panel to read more · × to return</span></footer></section></div>`;
  $('.modal-close').onclick=close;$('.modal-backdrop').onclick=e=>{if(e.target===e.currentTarget)close();};
  ($('.modal-body [data-focus]')||$('.modal-body [data-recipe]')||$('.modal-body [data-kit]')||$('.modal-body button:not(:disabled)')||$('.modal-close')).focus({preventScroll:true});
 }
 function close(){modal=null;$('#modal-root').innerHTML='';$('#hud').inert=false;clearKeys();$('#world').focus({preventScroll:true});}
 function choices(){return [...document.querySelectorAll('.modal button:not(:disabled),.modal select')];}
 function menuKey(e){
  if(!modal)return false;const k=e.key.toLowerCase();
  if(k==='escape'){e.preventDefault();close();return true;}
  if(['pageup','pagedown','home','end'].includes(k)&&e.target.tagName!=='SELECT'){
   e.preventDefault();const body=$('.modal-body');if(k==='home'||k==='end')body.scrollTop=k==='home'?0:body.scrollHeight;else body.scrollBy(0,body.clientHeight*(k==='pageup'?-.8:.8));return true;
  }
  if(['arrowup','arrowdown','w','s'].includes(k)&&!$('.modal-body button:not(:disabled)')){e.preventDefault();$('.modal-body').scrollBy(0,k==='arrowup'||k==='w'?-75:75);return true;}
  if(['arrowup','arrowdown','w','s','tab'].includes(k)&&e.target.tagName!=='SELECT'){
   e.preventDefault();const list=choices(),at=list.indexOf(document.activeElement),direction=k==='arrowup'||k==='w'||k==='tab'&&e.shiftKey?-1:1;const next=list[(at+direction+list.length)%list.length];next?.focus();next?.scrollIntoView({block:'nearest'});return true;
  }
  if(modal==='station'&&['q','r'].includes(k)){e.preventDefault();const tabs=[...document.querySelectorAll('[data-group]')];const i=tabs.findIndex(b=>b.dataset.group===group);tabs[(i+(k==='q'?-1:1)+tabs.length)%tabs.length]?.click();return true;}
  if((k==='enter'||k===' ')&&e.target.tagName!=='SELECT'){e.preventDefault();if(!e.repeat&&document.activeElement?.tagName==='BUTTON')document.activeElement.click();return true;}
  return true;
 }
 function showStation(id,preserve=false){
  const o=getStructure(s,id);if(!nearStructure(s,o))return toast('Walk up to the station first.');stationId=id;
  const focus=preserve?document.activeElement?.id:null;
  const def=BUILDABLES[o.kind],available=ALL_RECIPES.filter(r=>r.stations.includes(o.kind)),groups=[...new Set(available.map(r=>r.group))];
  if(!preserve){group=groups[0];batch=1;}if(!groups.includes(group))group=groups[0];
  const job=o.jobs[0],r=job&&RECIPE_BY_ID[job.recipe];
  const body=job?`<section class="job-card"><span class="eyebrow">${job.status==='ready'?'WAITING AT THIS STATION':'MATERIALS LOADED FROM YOUR BACKPACK'}</span><h3>${r.name}${job.count>1?' × '+job.count:''}</h3><p>${r.tool?'Your tool stays here until you return to collect it.':r.kit?'A portable building kit. Collect it, then place it wherever you settle.':names(job.output)+' will stay here until you collect it.'}</p><div id="job-time" class="job-time"></div><div class="job-track"><i id="job-progress"></i></div><div class="actions">${job.status==='ready'?'<button id="collect-job" class="primary" data-focus>Collect finished work <span class="keyboard-hint">[Enter]</span></button>':'<button id="leave-job" class="primary" data-focus>Leave it working · back to the woods</button><button id="cancel-job" class="secondary">Cancel and return materials</button>'}</div></section>`:available.length?`<div class="tabs">${groups.map(g=>`<button data-group="${g}" class="${g===group?'active':''}">${({materials:'Materials',tools:'Tools',workstations:'Workstations',house:'House & yard'})[g]}</button>`).join('')}</div><div class="batch-row"><span>Craft here. Collect here. <span class="keyboard-hint"><kbd>Q / R</kbd> switch tabs</span></span><label>Batch <select id="batch" aria-label="Crafting batch">${[1,5,10].map(n=>`<option ${n===batch?'selected':''}>${n}</option>`).join('')}</select></label></div><div class="recipe-list">${available.filter(r=>r.group===group).map(r=>{const count=r.tool?1:batch,block=recipeBlock(s,r,id,count);return `<button id="recipe-${r.id}" data-recipe="${r.id}" class="recipe ${block?'locked':''}" aria-disabled="${!!block}">${itemIcon(r.icon)}<div><strong>${r.name}</strong><p>${r.desc}</p><div class="cost">${costHTML(scaledCost(r.cost,count))}</div></div><div class="recipe-meta"><b>${block||'Start crafting →'}</b><span>${Math.ceil(jobDuration(s,r,count))}s${r.tool?'':r.kit?' · '+count+' kit'+(count>1?'s':''):' · '+names(jobOutput(r,o,count))}</span></div></button>`;}).join('')}</div>`:`<p class="note">${def.desc}</p>`;
  const idle=!o.jobs.length,canRest=['tent','bed','campfire'].includes(o.kind);
  open('station',def.name,def.desc,body+`<div class="station-note"><small>${o.kind==='tent'?'Make your first workbench here. Everything else grows from that.':def.station?'Every station runs one independent job. Build more to work in parallel.':'Move or pack this piece to rearrange your home.'}</small>${o.kind==='planter'?`<p class="note">${o.plant==='moonbell'?'A silver-blue moonbell is blooming here.':s.inventory.moonbell?'You have a moonbell cutting ready to plant.':'Find a moonbell cutting south of the giant’s grove.'}</p>${!o.plant?'<button id="plant-moonbell" class="primary" data-focus>Plant moonbell cutting</button>':''}`:''}${canRest?'<button id="rest-here" class="secondary">Rest until morning</button>':''}${o.kind==='festival'?'<button id="gather-table" class="primary">Gather your neighbors</button>':''}${!def.fixed?`<button id="move-piece" class="secondary" ${idle?'':'disabled'}>Move / rotate</button><button id="pack-piece" class="secondary" ${idle?'':'disabled'}>Pack up</button>`:''}</div>`,available.length||job?'':'small');
  document.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{group=b.dataset.group;showStation(id,true);});
  if($('#batch'))$('#batch').onchange=e=>{batch=Number(e.target.value);showStation(id,true);};
  document.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>{const r=RECIPE_BY_ID[b.dataset.recipe],result=startJob(s,id,r.id,r.tool?1:batch);if(result.error)return toast(result.error,'error');changed();showStation(id,true);playSound('build');});
  if($('#collect-job'))$('#collect-job').onclick=()=>{const result=collectStation(s,id);if(result.error)return toast(result.error,'error');changed();const kit=Object.keys(result.kits)[0];if(kit){close();beginPlacement(kit);toast(BUILDABLES[kit].name+' kit collected. Place it now, or '+(isTouch()?'tap Pack away':'press Esc')+' to keep it packed.');}else{toast(result.tool?(result.tool==='axe'?AXE_TIERS[s.axe].name:PICK_TIERS[s.pick].name)+' equipped.':'Collected '+names(result.output));showStation(id,true);}playSound('build');};
  if($('#leave-job'))$('#leave-job').onclick=close;
  if($('#cancel-job'))$('#cancel-job').onclick=()=>{const result=cancelJob(s,id);if(result.error)return toast(result.error,'error');changed();showStation(id,true);};
  if($('#plant-moonbell'))$('#plant-moonbell').onclick=()=>{const result=plantMoonbell(s,id);if(result.error)return toast(result.error,'error');changed(true);showStation(id);toast('The moonbell is planted. A little wild beauty, at home.');};
  if($('#rest-here'))$('#rest-here').onclick=()=>{const result=rest(s,o);if(result.error)return toast(result.error,'error');close();changed(true);toast('Day '+s.day+'. Stamina restored. Finished work is waiting at your stations.');};
  if($('#move-piece'))$('#move-piece').onclick=()=>beginPlacement(o.kind,id);
  if($('#pack-piece'))$('#pack-piece').onclick=()=>{const result=packStructure(s,id);if(result.error)return toast(result.error,'error');close();changed(true);toast(def.name+(isTouch()?' packed. Open Kits to place it again.':' packed. Press V to place it again.'));};
  if($('#gather-table'))$('#gather-table').onclick=()=>{if(!gatheringReady(s))return toast('A home and three good friends make a gathering. Your journal has their stories.');s.finished=true;changed();open('ending','Leave a seat for Everett.','A richer kind of life.','<p class="speech">Mara brings wildflowers. Jo fixes a wobbly chair. Nell brings supper. Everett brings a bottle he is trying very hard not to mention the price of.</p><p class="note">“Funny,” he says. “I spent all that money on a house, and you built a home.”</p><p class="note">The gathering is only one story. Your woods, workshops, and travels are still yours.</p>','small');};
  updateTimers();if(focus&&document.getElementById(focus))document.getElementById(focus).focus({preventScroll:true});
 }
 function updateTimers(){if(modal!=='station')return;const job=getStructure(s,stationId)?.jobs[0];if(!job||!$('#job-time'))return;$('#job-time').textContent=job.status==='ready'?'Ready to collect':Math.max(1,Math.ceil((job.readyAt-Date.now())/1000))+' seconds';$('#job-progress').style.width=(job.status==='ready'?100:Math.max(0,Math.min(100,(Date.now()-job.startedAt)/(job.readyAt-job.startedAt)*100)))+'%';}
 function refreshStation(){if(modal==='station')showStation(stationId,true);}
 function showBag(tab=bagTab){bagTab=tab;const kits=Object.entries(s.packed).filter(([,n])=>n>0),items=Object.entries(s.inventory).filter(([k,n])=>ITEMS[k]&&n>0);
  open('bag','A little of the woods.','Materials, tools, and pieces you have actually made.',`<div class="tabs"><button id="bag-items" class="${tab==='items'?'active':''}">Backpack</button><button id="bag-kits" class="${tab==='kits'?'active':''}">Packed kits · ${kits.reduce((a,[,n])=>a+n,0)}</button></div>${tab==='kits'?`<div class="recipe-list">${kits.map(([k,n])=>`<button class="recipe" data-kit="${k}">${itemIcon(BUILDABLES[k].icon)}<div><strong>${BUILDABLES[k].name}</strong><p>${n} packed · ${BUILDABLES[k].desc}</p></div><div class="recipe-meta"><b>Place →</b></div></button>`).join('')||'<p class="empty">No packed kits yet.<br>Use your tent to make your first workbench.<br>Use that workbench to make more stations and house pieces.</p>'}</div>`:`<div class="inventory-grid">${items.map(([k,n])=>`<div class="inventory-item">${itemIcon(k)}<div><strong>${ITEMS[k].name}</strong><small>${n} in your pack</small></div></div>`).join('')||'<p class="empty">The backpack is empty. Chop tiny saplings; gather loose stones and plants.</p>'}</div><p class="note">${AXE_TIERS[s.axe].name} · ${s.pick<0?'No pickaxe yet':PICK_TIERS[s.pick].name}<br>Your tools are equipped when collected from the right workstation.</p>`}`);
  $('#bag-items').onclick=()=>showBag('items');$('#bag-kits').onclick=()=>showBag('kits');document.querySelectorAll('[data-kit]').forEach(b=>b.onclick=()=>beginPlacement(b.dataset.kit));
 }
 function beginPlacement(kind,moveId=null){close();const original=moveId?getStructure(s,moveId):null;placement={kind,moveId,rotation:original?.rotation||0,snap:true,offset:{x:96,y:48},...snapPoint({x:s.player.x+96,y:s.player.y+48})};renderer.placement=placement;$('#placement-hud').hidden=false;$('#placement-hud').innerHTML=`<h3>${moveId?'Move':'Place'} ${BUILDABLES[kind].name}</h3><p id="placement-message"></p><div class="place-nudges touch-hint"><span>Nudge</span><button data-nudge="left" aria-label="Nudge outline left">←</button><button data-nudge="up" aria-label="Nudge outline up">↑</button><button data-nudge="down" aria-label="Nudge outline down">↓</button><button data-nudge="right" aria-label="Nudge outline right">→</button></div><div class="place-actions"><button id="confirm-place" class="confirm"><span class="keyboard-hint">Enter · </span>Place</button><button id="rotate-place"><span class="keyboard-hint">R · </span>Rotate</button><button id="grid-place"><span class="keyboard-hint">G · </span>Grid on</button><button id="cancel-place"><span class="keyboard-hint">Esc · </span>${moveId?'Cancel':'Pack away'}</button></div><small><span class="keyboard-hint">WASD moves Luke · Arrow keys move the outline · Mouse is optional.<br></span><span class="touch-hint">Tap or drag the outline onto clear ground. Use the stick to walk.<br></span>${moveId?'Cancelling leaves this piece where it was.':'Cancelling keeps the kit in your pack.'}</small>`;$('#confirm-place').onclick=commitPlacement;$('#rotate-place').onclick=rotate;$('#grid-place').onclick=toggleGrid;$('#cancel-place').onclick=cancelPlacement;document.querySelectorAll('[data-nudge]').forEach(b=>b.onclick=()=>nudge(b.dataset.nudge));updatePlacement();}
 function updatePlacement(){if(!placement)return;$('#game').classList.add('is-placing');const p=placement;Object.assign(p,snapPoint({x:s.player.x+p.offset.x,y:s.player.y+p.offset.y},p.snap));p.error=placementBlock(s,p.kind,p.x,p.y,p.rotation,p.moveId);$('#placement-message').textContent=p.error||`${p.rotation}° · Ready to place · ${p.moveId?'Move this piece':s.packed[p.kind]+' packed'}`;$('#placement-message').className=p.error?'invalid':'';$('#confirm-place').disabled=!!p.error;}
 function cancelPlacement(){placement=null;renderer.placement=null;$('#game').classList.remove('is-placing');$('#placement-hud').hidden=true;clearKeys();}
 function rotate(){if(!placement)return;placement.rotation=(placement.rotation+90)%360;updatePlacement();}
 function toggleGrid(){if(!placement)return;placement.snap=!placement.snap;$('#grid-place').innerHTML='<span class="keyboard-hint">G · </span>Grid '+(placement.snap?'on':'off');updatePlacement();}
 function nudge(direction){if(!placement)return;const delta=placement.snap?24:8;placement.offset.x+=direction==='left'?-delta:direction==='right'?delta:0;placement.offset.y+=direction==='up'?-delta:direction==='down'?delta:0;placement.offset.x=Math.max(-288,Math.min(288,placement.offset.x));placement.offset.y=Math.max(-288,Math.min(288,placement.offset.y));updatePlacement();}
 function commitPlacement(){if(!placement)return;const p=placement,result=p.moveId?moveStructure(s,p.moveId,p.x,p.y,p.rotation):placeStructure(s,p.kind,p.x,p.y,p.rotation);if(result.error)return toast(result.error,'error');changed(true);playSound('build');toast(BUILDABLES[p.kind].name+' placed.');if(!p.moveId&&s.packed[p.kind]>0)updatePlacement();else cancelPlacement();}
 function placementKey(e){if(!placement)return false;const k=e.key.toLowerCase();if(k==='escape')cancelPlacement();else if(k==='r')rotate();else if(k==='g')toggleGrid();else if(k==='enter'||k===' '){if(!e.repeat)commitPlacement();}else if(k.startsWith('arrow'))nudge(k.slice(5));else return false;e.preventDefault();return true;}
 function point(p){if(!placement)return;placement.offset={x:p.x-s.player.x,y:p.y-s.player.y};updatePlacement();}
 function showMap(){if(s.scene==='bunker'){open('map','Under the woods.','Explore branching service rooms, old living quarters, and mineral caverns. Unknown sectors appear as question marks.','<canvas id="large-map" class="map-canvas bunker-map" width="750" height="414" aria-label="Bunker floor plan"></canvas><p class="note">Gold blocks: timber or rock to chop or mine. Blue blocks: flooded passages. Red blocks: closed doors.<br>Interact to read notes, search lockers, and operate controls. Restore the generator, then run the drainage pumps. The return bulkhead opens from the barracks side.<br>The entrance stairs remain in the original western rooms, by Gerald. Cleared passages stay open.</p>');drawMap($('#large-map'),s);return;}open('map','The long way home.','One woodland. No fast travel. Follow trails, wander off them, and make your own way back.',`<canvas id="large-map" class="map-canvas" width="750" height="525" aria-label="Continuous woodland map"></canvas><p class="note">You are the bright dot. Small squares are your structures. The river is impassable except at the ${s.bridge?'repaired':'broken'} Mosswater crossing.<br>Pine Hollow is southwest of the river. Hemlock Ridge lies north. The mill and maple grove are on the eastern bank.</p>`);drawMap($('#large-map'),s);}
 function showJournal(){const home=houseProgress(s);open('journal','Make a life, your way.','Everett has a bigger house. That does not mean you need to live his life.',`<div class="journal-grid"><article class="journal-card"><h3>Make a home</h3><p>Design rooms, a garden, or a workshop village. More stations let you make more things at once.</p><small>${home.floors} floor tiles · ${home.walls} walls · ${home.beds} beds</small></article><article class="journal-card"><h3>Know the woods</h3><p>Six places hide caches, stories, and useful materials. The old mill holds advanced tool plans.</p><small>${Object.keys(s.discovered).length} / 6 discoveries · ${Object.keys(s.visited).length} / 7 places</small></article><article class="journal-card"><h3>Find your people</h3><p>Help neighbors whenever you like. Their rewards make foraging, crafting, and travelling easier.</p><small>${Object.values(s.helped).filter(Boolean).length} / 3 friendships</small></article></div>${Object.entries(SIDE_QUESTS).map(([id,q])=>`<article class="quest"><h3>${s.helped[id]?'✓ ':''}${q.name}</h3><p>${q.person} · ${q.place}<br>${s.helped[id]?q.thanks:s.accepted[id]?'Bring '+names(q.request)+'.':'Meet '+q.person+' to hear their story.'}</p><small>Reward: ${names(q.reward)} · ${q.perk}</small></article>`).join('')}${storyJournal()}<article class="quest"><h3>Places worth finding</h3>${Object.entries(DISCOVERIES).map(([id,d])=>`<p>${s.discovered[id]?'✓ '+d.name:'◇ '+({overlook:'A heron overlook northeast of the ridge',orchard:'An orchard west of the north trail',circle:'A stone circle in the far northwest',camp:'A survey camp in the southern woods',mill:'A millwright’s chest across the river',grove:'A giant’s grove in the eastern woods'})[id]}</p>`).join('')}</article>`);}
 function showPerson(n){if(n.person==='olga')return showOlga();if(n.person==='hermit')return showHermit();const person=n.person,p=PEOPLE[person],q=SIDE_QUESTS[person];let speech;
  if(person==='everett')speech=s.finished?'Everyone’s at your table again. I’ve got heated floors and a room just for shoes. Think there’s a spare chair?':houseProgress(s).complete?'You built all that yourself? I suppose there’s something to that. Don’t tell anyone I said so.':'Cute tent, Luke. Does it come in… house? I just put in an imported cedar sauna. Anyway, I’m the one with the actual front door.';
  else speech=s.helped[person]?q.thanks:q.quote;
  open('person',p.name,p.role,`<div class="person-heading">${portraitSVG(person)}<small>${person==='everett'?'His opinions are optional.':q.name}</small></div><p class="speech">“${speech}”</p>${q&&!s.helped[person]?`<p class="note">Bring ${names(q.request)}.<br>Reward: ${names(q.reward)} · ${q.perk}</p><div class="actions"><button id="quest-action" class="primary" data-focus>${s.accepted[person]?'I brought your supplies.':'I can help with that.'}</button><button id="person-leave" class="secondary">See you around.</button></div>`:'<div class="actions"><button id="person-leave" class="primary" data-focus>See you around the woods.</button></div>'}`,'small');
  $('#person-leave').onclick=close;if($('#quest-action'))$('#quest-action').onclick=()=>{if(!s.accepted[person]){s.accepted[person]=true;changed();toast(q.name+' added to your journal.');close();}else{const result=turnInQuest(s,person,n);if(result.error)return toast(result.error,'error');changed();showPerson(n);toast(q.perk);}};
 }
 function showBridge(){open('bridge','A way across.','Mosswater Brook · the eastern woods',`<p class="speech">${s.bridge?'New boards, old river. The other bank is yours to explore.':'The middle span has washed away. The river is too deep to wade. New planks and cord could put this crossing back together.'}</p>${s.bridge?'<p class="note">Walk across the bridge to reach the Old Sugarbush and Forgotten Mill.</p>':`<p class="note">${costHTML(BRIDGE_COST)}</p><div class="actions"><button id="repair-bridge" class="primary" data-focus>Repair the crossing</button></div>`}`,'small');if($('#repair-bridge'))$('#repair-bridge').onclick=()=>{const result=repairBridge(s);if(result.error)return toast(result.error,'error');close();changed(true);toast('The bridge is repaired. Walk across to the eastern woods.');playSound('build');};}
 function showHelp(){open('help','Find your own kind of rich.','Touch, mouse, or keyboard. The same woods, your way.',`<section class="touch-hint"><h3>Made for wandering.</h3><dl class="help-list touch-help"><dt>Walk</dt><dd>Tap open ground to walk there, or hold and slide the thumbstick. Toggle Run for longer journeys.</dd><dt>Chop / Mine</dt><dd>Tap a nearby resource or the action button once to work until it is depleted. Tap Stop, move, or choose another target to stop. Stamina and tool requirements still apply.</dd><dt>Interact</dt><dd>Gather, talk, read, or use a station. Next target cycles nearby objects, including overlapping house pieces.</dd><dt>Build</dt><dd>Choose a packed kit, then tap or drag its outline onto the ground. Nudge arrows place it precisely; Rotate and Grid help you design freely. Tap Place to confirm.</dd><dt>Explore</dt><dd>Map, Journal, Backpack, Kits, and Berries are always a tap away. + / − changes your view. Both phone orientations work.</dd></dl></section><h3 class="touch-hint">Keyboard controls still work</h3><dl class="help-list"><dt>W A S D</dt><dd>Walk continuously through the woods. The camera follows Luke.</dd><dt>Hold Space</dt><dd>Chop or mine the highlighted resource. The right tool is used automatically.</dd><dt>E · Tab</dt><dd>Interact with the highlighted station, neighbor, plant, or discovery. Tab cycles nearby targets.</dd><dt>B · V · F</dt><dd>Backpack · packed building kits · eat a blueberry.</dd><dt>M · J</dt><dd>Map · optional goals and neighbor stories.</dd><dt>Enter · ↑ ↓</dt><dd>Use menus without the mouse. Q / R switches workstation tabs.</dd><dt>Placing kits</dt><dd>WASD walks Luke. Arrows nudge the outline. R rotates, G toggles the grid, Enter places, Esc keeps it packed.</dd></dl><p class="note">Start by gathering 6 wood, 4 loose stone, and 2 fiber. Visit your tent to craft a workbench kit. Collect and place it. Your new workbench makes other stations, a mining pick, and house pieces.</p><h3>Small axe. Big possibilities.</h3><div class="progression">${TREE_TIERS.map((t,i)=>`<div><strong>${AXE_TIERS[i].name}</strong><span>${t.name} · ${t.logs} wood</span></div>`).join('')}</div><p class="note">Larger trees and rocks require better tools. Workstations keep your tool during an upgrade. Jobs finish while you explore—or sleep. Rest also replenishes resources without covering your buildings.</p>`);}
 function showSettings(){const controls=hooks.controls?.();open('settings','Take a breather.','Your woodland is saved automatically in this browser.',`<div class="actions"><button id="resume" class="primary" data-focus>Return to the woods</button><button id="sound" class="secondary">${s.sound?'Mute':'Enable'} woodland sounds</button><button id="show-help" class="secondary">How to play</button></div><label class="input-setting">Touch controls <select id="input-mode"><option value="auto" ${controls?.mode==='auto'?'selected':''}>Automatic</option><option value="on" ${controls?.mode==='on'?'selected':''}>Always show</option><option value="off" ${controls?.mode==='off'?'selected':''}>Hide</option></select></label><p class="note">Automatic shows thumb controls on a touchscreen. Keyboard and mouse controls always work.<br>Day ${s.day} · ${s.structures.length-1} placed pieces · ${Object.keys(s.discovered).length} discoveries.<br>Your adventure is saved locally; changing controls does not change your progress.</p>`,'small');$('#resume').onclick=close;$('#sound').onclick=()=>{s.sound=!s.sound;changed();showSettings();playSound('build');};$('#show-help').onclick=showHelp;$('#input-mode').onchange=e=>{controls?.setMode(e.target.value);showSettings();};}

 return {get modal(){return modal;},get placement(){return placement;},open,close,menuKey,showStation,refreshStation,updateTimers,showBag,beginPlacement,updatePlacement,placementKey,point,cancelPlacement,showMap,showJournal,showPerson,showStoryNode,showBridge,showHelp,showSettings};
}
